const fs=require("fs")
fs.writeFileSync('bio.txt','my name is dhiraj')
fs.appendFileSync('bio.txt',' how are you ')
const data=fs.readFileSync('bio.txt','utf-8')
console.log(data)
fs.unlinkSync("index.js/mybio.txt")